# Site settings
title: Ethan Moore
email: enm@EthanNMoore.com
description: > # this means to ignore newlines until "baseurl:"
  thoughts and essays
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ethannmoore.com" # the base hostname & protocol for your site
paginate: 1
paginate_path: "/page:num/"
twitter_username: etnmo
github_username: cathos

# Build settings
markdown: kramdown
